/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-08-26 06:52:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypageRead_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>MY PAGE</title>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("* {font-family:'@여기어때 잘난체';}\r\n");
      out.write("\r\n");
      out.write("#page {\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tmargin: 15px;\r\n");
      out.write("\tpadding-bottom:30px;\r\n");
      out.write("\theight: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content {\r\n");
      out.write("\tmargin-top:none;\r\n");
      out.write("\tmargin-left:70px;\r\n");
      out.write("\tmargin-right:70px;\r\n");
      out.write("\tpadding: 30px margin-top: 10px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content {\r\n");
      out.write(" \twidth:50%;\r\n");
      out.write("\tmargin:auto;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tborder-collapse:collapse;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td{\r\n");
      out.write("\tpadding:15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title{\r\n");
      out.write("\tfont-size:50px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tmargin:auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tbl1Title{\r\n");
      out.write("\tfont-size:40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=text],input[type=password] {\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btnShow input[type=button],.btnShowchk input[type=button],#btnCode,#emailSendInjeung,#phonecheck{\r\n");
      out.write("\theight: 55px;\r\n");
      out.write("\twidth:90px;\r\n");
      out.write("\toverflow:hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#previousPage{\r\n");
      out.write("\twidth:550px;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("\tmargin-top: 5px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tbackground: #e6bbea;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tborder:none;\r\n");
      out.write("\tborder-radius:3px 3px 3px 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btnUpdate{\r\n");
      out.write("\twidth:178px;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("\tmargin: 2px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tbackground: #e6bbea;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tborder:none;\r\n");
      out.write("\tborder-radius:3px 3px 3px 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btnCancel,#btnDelete{\r\n");
      out.write("\twidth:178px;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("\tmargin: 2px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tbackground: #969596;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tborder:none;\r\n");
      out.write("\tborder-radius:3px 3px 3px 3px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/menu.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div id=\"page\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<div class=\"title\">⊙ MY PAGE ⊙</div>\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<form name=\"frm\" action=\"/user/update\" method=\"post\">\r\n");
      out.write("\t\t\t\t<div class=\"btn\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" size=59 placeholder=\"　　ID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${users_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" maxlength=\"20\" name=\"users_id\" id=\"users_id\" readonly />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div class=\"btn\">\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" size=48 placeholder=\"　　PASSWORD\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.users_pass}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" maxlength=\"20\" name=\"users_pass\" class=\"pass\" /> \r\n");
      out.write("\t\t\t\t\t<span class=\"btnShow\"><input type=\"button\" value=\"SHOW\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div class=\"btn\">\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" size=48 placeholder=\"　　PASSWORD CHECK\" maxlength=\"20\" class=\"passchk\" /> \r\n");
      out.write("\t\t\t\t\t<span class=\"btnShowchk\"><input type=\"button\" value=\"SHOW\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t            \t<br><span id=\"users_passCHK\">비밀번호 확인</span>\r\n");
      out.write("         \t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div class=\"btn\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" size=59 placeholder=\"　　NAME\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.users_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"users_name\" id=\"users_name\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div class=\"btn\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" size=59 placeholder=\"　　BIRTHDAY\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.users_birthday}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"users_birthday\" id=\"users_birthday\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div class=\"btn\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" size=48 placeholder=\"　　ADDRESSS\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.users_zipcode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"users_zipcode\" id=\"users_zipcode\" readonly /> \r\n");
      out.write("\t\t\t\t\t<span><input type=\"button\" value=\"ZIP CODE\" id=\"btnCode\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div class=\"btn\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" size=59 placeholder=\"　　ADDRESS\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.users_address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"users_address\" id=\"users_address\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div class=\"btn\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" size=48 placeholder=\"　　PHONE NUMBER\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.users_phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"users_phone\" id=\"users_phone\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" id=\"phonecheck\" value=\"중복확인\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div class=\"btn\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" size=48 placeholder=\"　　E-MAIL\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.users_email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"users_email\" id=\"users_email\" readonly />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" id=\"emailSendInjeung\" value=\"UPDATE\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div class=\"btn\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"UPDATE\" id=\"btnUpdate\"/> \r\n");
      out.write("\t\t\t\t\t<input type=\"reset\" value=\"CANCEL\" id=\"btnCancel\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"DELETE\" id=\"btnDelete\"/><br>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"PREVIOUS PAGE\" id=\"previousPage\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/chat.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("passChk();\r\n");
      out.write("var phoneCHK=false;\r\n");
      out.write("var emailCHK=true;\r\n");
      out.write("var users_phonePre=$(\"#users_phone\").val();\r\n");
      out.write("var users_emailPre=$(\"#users_email\").val();\r\n");
      out.write("// 우편번호\r\n");
      out.write("   $(\"#btnCode\").on(\"click\", function(){\r\n");
      out.write("      openAddress();\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("// 우편번호\r\n");
      out.write("   function openAddress() {\r\n");
      out.write("      new daum.Postcode({\r\n");
      out.write("         oncomplete:function(data) {\r\n");
      out.write("            $(\"#users_zipcode\").val(data.zonecode);\r\n");
      out.write("            $(\"#users_address\").val(data.address);\r\n");
      out.write("            $(\"#users_address\").focus();\r\n");
      out.write("            }\r\n");
      out.write("      }).open();\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("// 수정버튼 클릭시\r\n");
      out.write("$(frm).submit(function(e){\r\n");
      out.write("   e.preventDefault();\r\n");
      out.write("   var users_pass=$(\".pass\").val();\r\n");
      out.write("   var users_passchk=$(\".passchk\").val();\r\n");
      out.write("   var users_name=$(\"#users_name\").val();\r\n");
      out.write("   var users_birthday=$(\"#users_birthday\").val();\r\n");
      out.write("   var users_zipcode=$(\"#users_zipcode\").val();\r\n");
      out.write("   var users_address=$(\"#users_address\").val();\r\n");
      out.write("   var users_phone=$(\"#users_phone\").val();\r\n");
      out.write("   var users_email=$(\"#users_email\").val();\r\n");
      out.write("   \r\n");
      out.write("   if(users_pass==\"\" || users_passchk==\"\" || users_name==\"\" || users_birthday==\"\" || users_zipcode==\"\" || users_address==\"\" || users_phone==\"\" || users_email==\"\"){\r\n");
      out.write("      alert(\"회원정보를 모두 입력해주세요.\");\r\n");
      out.write("   }else{\r\n");
      out.write("      \r\n");
      out.write("      if(users_phonePre!=users_phone) {\r\n");
      out.write("      if(phoneCHK==false) {\r\n");
      out.write("            alert(\"연락처 인증을 해주세요.\");\r\n");
      out.write("            return;\r\n");
      out.write("         }\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      if(emailCHK==false) {\r\n");
      out.write("            alert(\"이미 사용중인 이메일입니다.\");\r\n");
      out.write("            return;\r\n");
      out.write("         }\r\n");
      out.write("      \r\n");
      out.write("      if(!confirm(\"회원정보를 수정하시겠습니까?\")) return;\r\n");
      out.write("      \r\n");
      out.write("      alert(\"수정되었습니다.\");   \r\n");
      out.write("       frm.submit();\r\n");
      out.write("   }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("// 비밀번호 확인\r\n");
      out.write("function passChk(){\r\n");
      out.write("   $(\".pass, .passchk\").change(function(){\r\n");
      out.write("      var users_pass=$(\".pass\").val();\r\n");
      out.write("      var users_passChk=$(\".passchk\").val();\r\n");
      out.write("      \r\n");
      out.write("      if(users_pass==users_passChk){\r\n");
      out.write("         $(\"#users_passCHK\").html(\"비밀번호가 일치합니다.\");\r\n");
      out.write("      }else if(users_pass!=users_passChk){\r\n");
      out.write("         $(\"#users_passCHK\").html(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      if(users_pass==\"\" || users_passChk==\"\"){\r\n");
      out.write("         $(\"#users_passCHK\").html(\"\");\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(\"#previousPage\").on(\"click\", function(){\r\n");
      out.write("   location.href=\"/user/mypage\";\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("//mouseOver   \r\n");
      out.write("$(\".btnShow\").mouseover(function(){\r\n");
      out.write("   $(\".btn .pass\").prop(\"type\", \"text\");\r\n");
      out.write("});\r\n");
      out.write("$(\".btnShow\").mouseout(function(){\r\n");
      out.write("   $(\".btn .pass\").prop(\"type\", \"password\");\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//mouseOver   \r\n");
      out.write("$(\".btnShowchk\").mouseover(function(){\r\n");
      out.write("   $(\".btn .passchk\").prop(\"type\", \"text\");\r\n");
      out.write("});\r\n");
      out.write("$(\".btnShowchk\").mouseout(function(){\r\n");
      out.write("   $(\".btn .passchk\").prop(\"type\", \"password\");\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var email=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("$(\"#emailSendInjeung\").on(\"click\", function(){\r\n");
      out.write("   var options = 'width=500, height=500, top=30, left=30, resizable=no, scrollbars=no, location=no';\r\n");
      out.write("    window.open('/user/emailUpdate', 'Update', options);    \r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("/*연락처중복확인*/\r\n");
      out.write("   $(\"#phonecheck\").on(\"click\", function(){\r\n");
      out.write("      var users_phone=$(\"#users_phone\").val();\r\n");
      out.write("      users_phone=users_phone.replace(/(^02.{0}|^01.{1}|[0-9]{3})([0-9]+)([0-9]{4})/,\"$1-$2-$3\");\r\n");
      out.write("      \r\n");
      out.write("      if(users_phone==\"\"){\r\n");
      out.write("         alert(\"연락처를 입력해주세요!\");\r\n");
      out.write("         return;\r\n");
      out.write("      }else{\r\n");
      out.write("         $.ajax({\r\n");
      out.write("            type:\"get\",\r\n");
      out.write("            url:\"/user/pcheck\",\r\n");
      out.write("            data:{\"users_phone\":users_phone},\r\n");
      out.write("            success:function(data){\r\n");
      out.write("               if(data==2){\r\n");
      out.write("                  alert(\"사용가능한 연락처입니다.\");\r\n");
      out.write("                  phoneCHK=true;\r\n");
      out.write("                  $(\"#users_phone\").val(users_phone);\r\n");
      out.write("               }else{\r\n");
      out.write("                  alert(\"이미 사용중인 연락처입니다.\");\r\n");
      out.write("                  phoneCHK=false;\r\n");
      out.write("                  $(\"#users_phone\").val(users_phone);\r\n");
      out.write("               }\r\n");
      out.write("            }\r\n");
      out.write("         });\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(\"#btnDelete\").on(\"click\", function(){\r\n");
      out.write("   if(!confirm(\"회원 탈퇴하시겠습니까?\")) return; \r\n");
      out.write("   if(!confirm(\"탈퇴한 계정을 복구하고 싶으시면 운영자한테 문의해주세요.\")) return; \r\n");
      out.write("   alert(\"회원 탈퇴되었습니다!\");\r\n");
      out.write("   frm.action=\"/user/delete\";\r\n");
      out.write("   frm.submit();\r\n");
      out.write("   \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write(" $(frm.reset).on(\"click\", function(){\r\n");
      out.write("   emailCHK=true;\r\n");
      out.write("});\r\n");
      out.write(" \r\n");
      out.write(" $(\"#users_phone\").change(function(){\r\n");
      out.write("      phoneCHK=false;\r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
