/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-08-26 06:52:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>MY PAGE</title>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("* {font-family:'@여기어때 잘난체';}\r\n");
      out.write("\r\n");
      out.write("#page {\r\n");
      out.write("   background: white;\r\n");
      out.write("   margin: 15px;\r\n");
      out.write("   padding-bottom:30px;\r\n");
      out.write("   height: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content {\r\n");
      out.write("    display:inline-block;\r\n");
      out.write("    margin:5%;\r\n");
      out.write("   margin-top: 10px;\r\n");
      out.write("   margin-bottom: 40px;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   width: 90%;\r\n");
      out.write("   height:hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tbl1 {\r\n");
      out.write("   width:100%;\r\n");
      out.write("   margin:auto;\r\n");
      out.write("   overflow: hidden;\r\n");
      out.write("   border-collapse:collapse;\r\n");
      out.write("   margin-bottom:50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tbl2{\r\n");
      out.write("   float:left;\r\n");
      out.write("   width:48%;\r\n");
      out.write("   overflow: hidden;\r\n");
      out.write("   border-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tbl3 {\r\n");
      out.write("   float:right;\r\n");
      out.write("   width:48%;\r\n");
      out.write("   overflow: hidden;\r\n");
      out.write("   border-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#COSTUME,#PACKAGE{\r\n");
      out.write("   color:#e360f2;\r\n");
      out.write("   font-size: 30px;\r\n");
      out.write("   text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td{\r\n");
      out.write("   padding: 15px;\r\n");
      out.write("   border-bottom:1px solid #e360f2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("   padding: 15px;\r\n");
      out.write("   font-size: 20px;\r\n");
      out.write("   border-bottom:3px solid #e360f2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tbl1 th{\r\n");
      out.write("    width:50%;\r\n");
      out.write("   font-size:40px;\r\n");
      out.write("}\r\n");
      out.write(".row{\r\n");
      out.write("   height: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title{\r\n");
      out.write("   font-size:50px;\r\n");
      out.write("   text-align:center;\r\n");
      out.write("   margin:auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".userUpdate{\r\n");
      out.write("   cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".userUpdate:hover{\r\n");
      out.write("   border-radius: 50px 50px 50px 50px;\r\n");
      out.write("   background:#e360f2;\r\n");
      out.write("   color:white;\r\n");
      out.write("}\r\n");
      out.write(".img{\r\n");
      out.write("   border:0px;\r\n");
      out.write("}\r\n");
      out.write(".orderday{\r\n");
      out.write("   font-size:13px;\r\n");
      out.write("}\r\n");
      out.write("img:hover{\r\n");
      out.write("   cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".code{\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write(".no{\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write(".X{\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tcolor:red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pcprice{\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/menu.jsp", out, false);
      out.write("\r\n");
      out.write("   <div id=\"page\">\r\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/header.jsp", out, false);
      out.write("\r\n");
      out.write("      <div class=\"title\">⊙ MY PAGE ⊙</div>\r\n");
      out.write("      <br><br>\r\n");
      out.write("      <div id=\"content\">\r\n");
      out.write("         <table id=\"tbl1\">\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th>\r\n");
      out.write("                  <span id=\"point\"></span> Point\r\n");
      out.write("               </th>\r\n");
      out.write("               <th class=\"userUpdate\">MY INFO UPDATE</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("         </table><br>\r\n");
      out.write("         <table id=\"tbl2\"></table>\r\n");
      out.write("         <script id=\"temp2\" type=\"text/x-handlebars-template\">\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th colspan=7 id=\"PACKAGE\">PACKAGE ORDER</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("         <tr class=\"th\">\r\n");
      out.write("                  <th>IMAGE</th>\r\n");
      out.write("                  <th width=150>PACKAGE</th>\r\n");
      out.write("\t\t\t\t\t<th width=50></th>\r\n");
      out.write("                  <th>PRICE</th>\r\n");
      out.write("                  <th width=137>PAY TYPE</th>\r\n");
      out.write("                  <th>TOTAL</th>\r\n");
      out.write("\t\t\t\t\t<th width=30></th>\r\n");
      out.write("               </tr>\r\n");
      out.write("            {{#each packagelist}}\r\n");
      out.write("               <tr class=\"row\">\r\n");
      out.write("                  <td class=\"img\">\r\n");
      out.write("                <img src=\"../display?fileName={{photo_package_image}}\" width=110/>\r\n");
      out.write("               </td>\r\n");
      out.write("               <td rowspan=3>{{photo_package_title}}</td>\r\n");
      out.write("                  <td rowspan=3>{{orders_package_quantity}}개</td>\r\n");
      out.write("                  <td rowspan=3 class=\"pcprice\">{{package_cart_price}}원</td>\r\n");
      out.write("                  <td rowspan=3>{{printStyle orders_paytype}}</td>\r\n");
      out.write("                  <td rowspan=3 class=\"pcprice\">{{total}}원</td>\r\n");
      out.write("\t\t\t\t\t<td rowspan=3><button class=\"X\">X</button></td>\r\n");
      out.write("               <td class=\"code\">{{photo_package_code}}</td>\r\n");
      out.write("            \t<td class=\"no\">{{orders_no}}</td>\r\n");
      out.write("               <tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td class=\"orderday\">\r\n");
      out.write("                      <b>{{orders_day}}</b>\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("            {{/each}}\r\n");
      out.write("         </script>\r\n");
      out.write("         <table id=\"tbl3\"></table>\r\n");
      out.write("         <script id=\"temp3\" type=\"text/x-handlebars-template\">\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th colspan=7 id=\"COSTUME\">COSTUME ORDER</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("         <tr class=\"th\">\r\n");
      out.write("                  <th>IMAGE</th>\r\n");
      out.write("                  <th width=150>COSTUME</th>\r\n");
      out.write("\t\t\t\t\t<th width=50></th>\r\n");
      out.write("                  <th>PRICE</th>\r\n");
      out.write("                  <th width=137>PAY TYPE</th>\r\n");
      out.write("                   <th>TOTAL</th>\r\n");
      out.write("\t\t\t\t\t<th width=30></th>\r\n");
      out.write("               </tr>\r\n");
      out.write("            {{#each costumelist}}\r\n");
      out.write("               <tr class=\"row\">\r\n");
      out.write("                  <td class=\"img\"><img src=\"../display?fileName={{lend_costume_image}}\" width=110/></td>\r\n");
      out.write("                  <td rowspan=3>{{lend_costume_name}}</td>\r\n");
      out.write("                 <td rowspan=3>{{orders_costume_quantity}}개</td>\r\n");
      out.write("                  <td rowspan=3 class=\"pcprice\">{{costume_cart_price}}원</td>\r\n");
      out.write("                  <td rowspan=3>{{printStyle2 orders_paytype}}</td>\r\n");
      out.write("                  <td rowspan=3 class=\"pcprice\">{{total}}원</td>\r\n");
      out.write("\t\t\t\t\t<td rowspan=3><button class=\"X\">X</button></td>\r\n");
      out.write("                 <td class=\"code\">{{lend_costume_code}}</td>\r\n");
      out.write("             <td class=\"no\">{{orders_no}}</td>\r\n");
      out.write("               <tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td class=\"orderday\">\r\n");
      out.write("                     <b>{{orders_day}}</b>\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("            {{/each}}\r\n");
      out.write("         </script>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/chat.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/top.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("   var users_id=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${users_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("   getpackageList();\r\n");
      out.write("   getcostumeList();\r\n");
      out.write("   getPoint();\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   var orders_paytype=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.orders_paytype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("   \r\n");
      out.write("   Handlebars.registerHelper(\"printStyle\",function(type){\r\n");
      out.write("         var src;\r\n");
      out.write("         if(orders_paytype == type) {\r\n");
      out.write("            src=\"카카오 결제\";\r\n");
      out.write("         } else if(orders_paytype != type) {\r\n");
      out.write("            src=\"현금결제\";\r\n");
      out.write("         }\r\n");
      out.write("         return src;\r\n");
      out.write("         \r\n");
      out.write("      });\r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write("   $(\"#tbl2\").on(\"click\", \".row button\",function(){\r\n");
      out.write("      var orders_no=$(this).parent().parent().find(\".no\").html();\r\n");
      out.write("      \r\n");
      out.write("        $.ajax({\r\n");
      out.write("            type:\"get\",\r\n");
      out.write("            url:\"/order/packageStatusUp\",\r\n");
      out.write("            data:{\"orders_no\":orders_no},\r\n");
      out.write("            success:function(){\r\n");
      out.write("            \tgetpackageList();\r\n");
      out.write("              alert(\"내역이 삭제되었습니다.\");\r\n");
      out.write("            }\r\n");
      out.write("         }); \r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("$(\"#tbl3\").on(\"click\", \".row button\",function(){\r\n");
      out.write("   var orders_no=$(this).parent().parent().find(\".no\").html();\r\n");
      out.write("      \r\n");
      out.write("       $.ajax({\r\n");
      out.write("            type:\"get\",\r\n");
      out.write("            url:\"/order/costumeStatusUp\",\r\n");
      out.write("            data:{\"orders_no\":orders_no},\r\n");
      out.write("            success:function(){\r\n");
      out.write("            \tgetcostumeList();\r\n");
      out.write("              alert(\"내역이 삭제되었습니다.\");\r\n");
      out.write("            }\r\n");
      out.write("         }); \r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   Handlebars.registerHelper(\"printStyle2\",function(type){\r\n");
      out.write("         var src;\r\n");
      out.write("         if(orders_paytype == type) {\r\n");
      out.write("            src=\"카카오 결제\";\r\n");
      out.write("         } else if(orders_paytype != type) {\r\n");
      out.write("            src=\"현금결제\";\r\n");
      out.write("         }\r\n");
      out.write("         return src;\r\n");
      out.write("         \r\n");
      out.write("      });\r\n");
      out.write("   \r\n");
      out.write("   function getpackageList(){\r\n");
      out.write("      $.ajax({\r\n");
      out.write("         type:\"get\",\r\n");
      out.write("         url:\"/order/packagelist\",\r\n");
      out.write("         data:{\"users_id\":users_id},\r\n");
      out.write("         dataType:\"json\",\r\n");
      out.write("         success:function(data){\r\n");
      out.write("            var temp=Handlebars.compile($(\"#temp2\").html());\r\n");
      out.write("            var aa=temp(data);\r\n");
      out.write("            aa=aa.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, \",\");\r\n");
      out.write("            $(\"#tbl2\").html(aa);\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   function getcostumeList(){\r\n");
      out.write("         $.ajax({\r\n");
      out.write("            type:\"get\",\r\n");
      out.write("            url:\"/order/costumelist\",\r\n");
      out.write("            data:{\"users_id\":users_id},\r\n");
      out.write("            dataType:\"json\",\r\n");
      out.write("            success:function(data){\r\n");
      out.write("               var temp=Handlebars.compile($(\"#temp3\").html());\r\n");
      out.write("               var bb=temp(data);\r\n");
      out.write("               bb=bb.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, \",\");\r\n");
      out.write("               $(\"#tbl3\").html(bb);\r\n");
      out.write("            }\r\n");
      out.write("         });\r\n");
      out.write("      }\r\n");
      out.write("   \r\n");
      out.write("   function getPoint(){\r\n");
      out.write("      $.ajax({\r\n");
      out.write("         type:\"get\",\r\n");
      out.write("         url:\"/user/point\",\r\n");
      out.write("         data:{\"users_id\":users_id},\r\n");
      out.write("         dataType:\"json\",\r\n");
      out.write("         success:function(data){\r\n");
      out.write("        \t var data=data.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, \",\");\r\n");
      out.write("            $(\"#point\").html(data);\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   /*UPDATE클릭 했을때 이동*/\r\n");
      out.write("   $(\".userUpdate\").on(\"click\", function(){\r\n");
      out.write("      location.href=\"/user/read\";\r\n");
      out.write("   })\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   $(\"#tbl2\").on(\"click\", \".row img\", function(){\r\n");
      out.write("      var code=$(this).parent().parent().find(\".code\").html();\r\n");
      out.write("      location.href=\"/packageRead?photo_package_code=\"+code\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   $(\"#tbl3\").on(\"click\", \".row img\", function(){\r\n");
      out.write("      var code=$(this).parent().parent().find(\".code\").html();\r\n");
      out.write("      location.href=\"/costumeRead?lend_costume_code=\"+code\r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
