/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-08-19 06:53:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class purchase_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1592786321749L));
    _jspx_dependants.put("jar:file:/C:/data/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FINAL/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/data/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FINAL/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<title>PURCHASE</title>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.iamport.kr/js/iamport.payment-1.1.5.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("* {font-family:'@여기어때 잘난체'}\r\n");
      out.write("\r\n");
      out.write("#page {\r\n");
      out.write("   background: white;\r\n");
      out.write("   margin: 15px;\r\n");
      out.write("   padding-bottom:30px;\r\n");
      out.write("   height: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content {\r\n");
      out.write("    display:inline-block;\r\n");
      out.write("    margin:5%;\r\n");
      out.write("   margin-top: 10px;\r\n");
      out.write("   margin-bottom: 40px;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   width: 90%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tbl1 {\r\n");
      out.write("   width:100%;\r\n");
      out.write("   margin:auto;\r\n");
      out.write("   overflow: hidden;\r\n");
      out.write("   border-collapse:collapse;\r\n");
      out.write("   margin-bottom:50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tbl2{\r\n");
      out.write("   float:left;\r\n");
      out.write("   width:48%;\r\n");
      out.write("   overflow: hidden;\r\n");
      out.write("   border-collapse: collapse;\r\n");
      out.write("   margin-bottom:50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tbl3 {\r\n");
      out.write("   float:right;\r\n");
      out.write("   width:48%;\r\n");
      out.write("   overflow: hidden;\r\n");
      out.write("   border-collapse: collapse;\r\n");
      out.write("   margin-bottom:50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#COSTUME,#PACKAGE{\r\n");
      out.write("   color:#e360f2;\r\n");
      out.write("   font-size: 30px;\r\n");
      out.write("   text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td{\r\n");
      out.write("   padding: 15px;\r\n");
      out.write("   border-bottom:1px solid #e360f2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tbl1 td{\r\n");
      out.write("   padding: 15px;\r\n");
      out.write("   border-bottom:3px solid #e360f2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("   padding: 15px;\r\n");
      out.write("   font-size: 20px;\r\n");
      out.write("   border-bottom:3px solid #e360f2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row{\r\n");
      out.write("   height: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title{\r\n");
      out.write("   font-size:50px;\r\n");
      out.write("   text-align:center;\r\n");
      out.write("   margin:auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#divFinal{\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   width:100%;\r\n");
      out.write("   margin: auto;\r\n");
      out.write("   height:300px;\r\n");
      out.write("   padding-left:15%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#divSum, #divShipping, #divtotalSum{\r\n");
      out.write("   padding-top:80px;\r\n");
      out.write("   padding-bottom:80px;\r\n");
      out.write("   border: 1px solid #e360f2;\r\n");
      out.write("   display: block;\r\n");
      out.write("   width: 300px;\r\n");
      out.write("   height: hidden;\r\n");
      out.write("   display: table-cell;\r\n");
      out.write("   vertical-align: middle;\r\n");
      out.write("   float:left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#divPoint {\r\n");
      out.write("   padding-top:60px;\r\n");
      out.write("   padding-bottom:60px;\r\n");
      out.write("   border: 1px solid #e360f2;\r\n");
      out.write("   display: block;\r\n");
      out.write("   width: 300px;\r\n");
      out.write("   height: hidden;\r\n");
      out.write("   display: table-cell;\r\n");
      out.write("   vertical-align: middle;\r\n");
      out.write("   float:left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#divSum input[type='text'],#divShipping input[type='text'],#divtotalSum input[type='text'],#divPoint input[type='text']{\r\n");
      out.write("   width: 100px;\r\n");
      out.write("   height: 40px;\r\n");
      out.write("   margin-top: 7px;\r\n");
      out.write("   margin-bottom: 5px;\r\n");
      out.write("   text-align: right;\r\n");
      out.write("   font-size: 20px;\r\n");
      out.write("   color: #dc1c2c;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   outline: none;\r\n");
      out.write("   border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divOper div {\r\n");
      out.write("   margin-top: 250%;\r\n");
      out.write("   font-size: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divOper {\r\n");
      out.write("   display: block;\r\n");
      out.write("   height: 200px;\r\n");
      out.write("   width: 50px;\r\n");
      out.write("   float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".OrderArea {\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".totalDel{\r\n");
      out.write("   width: 73px;\r\n");
      out.write("   height: 30px;\r\n");
      out.write("   font-size: 13px;\r\n");
      out.write("   margin-right: 18%;\r\n");
      out.write("   cursor: pointer;\r\n");
      out.write("   background: #e6bbea;\r\n");
      out.write("   color: white;\r\n");
      out.write("   border: none;\r\n");
      out.write("   border-radius: 3px 3px 3px 3px;\r\n");
      out.write("   font-weight:lighter;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btnUpdate{\r\n");
      out.write("   width: 50px;\r\n");
      out.write("   height: 25px;\r\n");
      out.write("   font-size: 13px;\r\n");
      out.write("   cursor: pointer;\r\n");
      out.write("   background: #e6bbea;\r\n");
      out.write("   color: white;\r\n");
      out.write("   border: none;\r\n");
      out.write("   border-radius: 3px 3px 3px 3px;\r\n");
      out.write("   font-weight:lighter;\r\n");
      out.write("   margin:auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"number\"]{\r\n");
      out.write("   margin-bottom:5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".photo_package_title{\r\n");
      out.write("   overflow:hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".img{\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btnKakao {\r\n");
      out.write("  margin-top: 50px;\r\n");
      out.write("   margin-right: 15px;\r\n");
      out.write("   border: 1px solid #e360f2;\r\n");
      out.write("   border-radius: 4px 4px 4px 4px;\r\n");
      out.write("   background: #e360f2;\r\n");
      out.write("   color: white;\r\n");
      out.write("   font-size:30px;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   outline: none;\r\n");
      out.write("   cursor: pointer;\r\n");
      out.write("   padding:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btn,#reset{\r\n");
      out.write("   height: 25px;\r\n");
      out.write("   font-size: 13px;\r\n");
      out.write("   cursor: pointer;\r\n");
      out.write("   background: #e6bbea;\r\n");
      out.write("   color: white;\r\n");
      out.write("   border: none;\r\n");
      out.write("   border-radius: 3px 3px 3px 3px;\r\n");
      out.write("   font-weight:lighter;\r\n");
      out.write("   margin:auto;\r\n");
      out.write("   padding-right:5px;\r\n");
      out.write("   padding-left:5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#divtotalSum input[type=\"text\"]{\r\n");
      out.write("color:red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/menu.jsp", out, false);
      out.write("\r\n");
      out.write("   <div id=\"page\">\r\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/header.jsp", out, false);
      out.write("\r\n");
      out.write("      <div class=\"title\">⊙ PURCHASE ⊙</div>\r\n");
      out.write("      <br><br>\r\n");
      out.write("      <div id=\"content\">\r\n");
      out.write("\t<table id=\"tbl1\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>NAME</th>\r\n");
      out.write("\t\t\t<th>BIRTHDAY</th>\r\n");
      out.write("\t\t\t<th>ZIP CODE</th>\r\n");
      out.write("\t\t\t<th>ADRESS</th>\r\n");
      out.write("\t\t\t<th>TEL</th>\r\n");
      out.write("\t\t\t<th>E-MAIL</th>\r\n");
      out.write("\t\t\t<th>POINT</th>\r\n");
      out.write("\t\t\t<th>GENDER</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.users_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.users_birthday}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.users_zipcode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.users_address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.users_phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.users_email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.users_point}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.users_gender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<table id=\"tbl2\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("            <th colspan=6 id=\"PACKAGE\">PACKAGE ORDER</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>NO.</th>\r\n");
      out.write("\t\t\t<th width=150>TITLE</th>\r\n");
      out.write("\t\t\t<th>IMAGE</th>\r\n");
      out.write("\t\t\t<th>QAUNTITY</th>\r\n");
      out.write("\t\t\t<th>PRICE</th>\r\n");
      out.write("\t\t\t<th>TOTAL PRICE</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<table id=\"tbl3\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("            <th colspan=6 id=\"COSTUME\">COSTUME ORDER</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>NO.</th>\r\n");
      out.write("\t\t\t<th width=150>TITLE</th>\r\n");
      out.write("\t\t\t<th>IMAGE</th>\r\n");
      out.write("\t\t\t<th>QAUNTITY</th>\r\n");
      out.write("\t\t\t<th>PRICE</th>\r\n");
      out.write("\t\t\t<th>TOTAL PRICE</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div id=\"divFinal\">\r\n");
      out.write("\t\t\t<div id=\"divSum\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h2>PACKAGE</h2>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"packageSum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${psum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly> 원\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"divOper\">\r\n");
      out.write("\t\t\t\t<div>+</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"divShipping\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h2>COSTUME</h2>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"costumeSum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${csum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly> 원\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"divOper\">\r\n");
      out.write("\t\t\t\t<div>-</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<form>\r\n");
      out.write("\t\t\t<div id=\"divPoint\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h2>POINT</h2>\r\n");
      out.write("\t\t\t\t\tMY POINT : <span id=\"myPoint\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${point}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span><br>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"point\" value=\"0\" > 원<br>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"사용하기\" id=\"btn\">\r\n");
      out.write("\t\t\t\t\t<input type=\"reset\" value=\"초기화\" id=\"reset\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"divOper\">\r\n");
      out.write("\t\t\t\t<div>=</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"divtotalSum\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h2>TOTAL</h2>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"totalSum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${psum+csum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly> 원 <br>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" value=\"");
      if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_page_context))
        return;
      out.write("\" id=\"money\" readonly> p 적립 예정<br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("         <div class=\"OrderArea\">\r\n");
      out.write("\t\t<button id=\"btnKakao\">카카오페이결제</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("      </div>\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/chat.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/top.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("   $(\"#tbl2 .no\").hide();\r\n");
      out.write("   $(\"#tbl3 .no\").hide();\r\n");
      out.write("   var point=\"0\";\r\n");
      out.write("   \r\n");
      out.write("   /*포인트 사용*/\r\n");
      out.write("   $(\"#btn\").on(\"click\", function(){\r\n");
      out.write("      var totalSum=parseInt($(\"#totalSum\").val());\r\n");
      out.write("      var myPoint=parseInt($(\"#myPoint\").html());\r\n");
      out.write("      point=parseInt($(\"#point\").val());\r\n");
      out.write("\t  $(\"#money\").val((totalSum-point)*0.01);\r\n");
      out.write("      if(point<=myPoint) {\r\n");
      out.write("         $(\"#totalSum\").val(totalSum-point);\r\n");
      out.write("         $(\"#btn\").attr('disabled', true);\r\n");
      out.write("      } else if(point>myPoint){\r\n");
      out.write("         alert(\"보유한 포인트를 초과합니다.\");\r\n");
      out.write("         $(\"#point\").val(\"\");\r\n");
      out.write("         $(\"#point\").focus();\r\n");
      out.write("         return;\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("      \r\n");
      out.write("   $(\"#reset\").on(\"click\", function(){\r\n");
      out.write("      $(\"#btn\").attr('disabled', false);\r\n");
      out.write("      $(\"#point\").val(\"\");\r\n");
      out.write("      $(\"#point\").focus();\r\n");
      out.write("      point=\"0\";\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   /*카카오페이*/\r\n");
      out.write("   $(\"#btnKakao\").on(\"click\", function() {\r\n");
      out.write("\t  var totalSum = $(\"#totalSum\").val();\r\n");
      out.write("      var IMP = window.IMP;\r\n");
      out.write("      \r\n");
      out.write("      IMP.init(\"imp56975225\");\r\n");
      out.write("      IMP.request_pay({\r\n");
      out.write("         pg : \"kakaopay\",\r\n");
      out.write("         pay_method : 'card',\r\n");
      out.write("         merchant_uid : 'merchant_' + new Date().getTime(),\r\n");
      out.write("         name : \"패키지+코스튬\",\r\n");
      out.write("         amount : totalSum,\r\n");
      out.write("         buyer_email : 'iamport@siot.do',\r\n");
      out.write("         buyer_name : \"홍길동\",\r\n");
      out.write("         buyer_tel : '010-1234-5678',\r\n");
      out.write("         buyer_addr : '서울특별시 강남구 삼성동',\r\n");
      out.write("         buyer_postcode : '123-456'\r\n");
      out.write("      }, function(rsp) {\r\n");
      out.write("         if (rsp.success) {\r\n");
      out.write("            var packageNO = new Array();\r\n");
      out.write("            var costumeNO = new Array();\r\n");
      out.write("            var packageQuantity = new Array();\r\n");
      out.write("            var costumeQuantity = new Array();\r\n");
      out.write("            var users_id = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${users_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("            var orders_paytype=\"0\";\r\n");
      out.write("            \r\n");
      out.write("            $(\"#tbl2 .row .no\").each(function() {\r\n");
      out.write("               var package_cart_no=$(this).parent().find(\".no\").html();\r\n");
      out.write("               var package_quantity=$(this).parent().find(\".quantity\").html();\r\n");
      out.write("               packageNO.push(package_cart_no);\r\n");
      out.write("               packageQuantity.push(package_quantity);\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            $(\"#tbl3 .row .no\").each(function() {\r\n");
      out.write("               var costume_cart_no=$(this).parent().find(\".no\").html();\r\n");
      out.write("               var costume_quantity=$(this).parent().find(\".quantity\").html();\r\n");
      out.write("               costumeNO.push(costume_cart_no);\r\n");
      out.write("               costumeQuantity.push(costume_quantity);\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            var totalsum=$(\"#totalSum\").val();\r\n");
      out.write("            \r\n");
      out.write("            $.ajax({\r\n");
      out.write("               type : \"post\",\r\n");
      out.write("               url : \"/order/insert\",\r\n");
      out.write("               data : {\"packageNO[]\":packageNO, \"costumeNO[]\":costumeNO, \r\n");
      out.write("            \t   \"packageQuantity[]\":packageQuantity, \"costumeQuantity[]\":costumeQuantity,\r\n");
      out.write("            \t   \"orders_paytype\":orders_paytype, \"orders_id\":users_id, \"totalsum\":totalsum,\r\n");
      out.write("            \t   \"point\":point},\r\n");
      out.write("               success : function() {\r\n");
      out.write("                  location.href=\"/user/mypage?users_id=\"+users_id;\r\n");
      out.write("               }\r\n");
      out.write("            });\r\n");
      out.write("            var msg = '결제가 완료되었습니다.';\r\n");
      out.write("         } else {\r\n");
      out.write("            var msg = '결제가 취소되었습니다.';\r\n");
      out.write("         }\r\n");
      out.write("         alert(msg);\r\n");
      out.write("      });\r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/user/purchase.jsp(264,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/purchase.jsp(264,2) '${plist}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${plist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/user/purchase.jsp(264,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("vo");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<tr class=\"row\">\r\n");
          out.write("\t\t\t\t<td class=\"no\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.package_cart_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.photo_package_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.photo_package_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t<td><img class=\"img\" src=\"../display?fileName=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.photo_package_image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" width=110 onClick=\"location.href='/costume/costumeRead?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.photo_package_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("'\"></td>\r\n");
          out.write("\t\t\t\t<td class=\"quantity\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.package_cart_quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.package_cart_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("원</td>\r\n");
          out.write("\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.package_cart_price*vo.package_cart_quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("원</td>\r\n");
          out.write("\t\t\t</tr>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /WEB-INF/views/user/purchase.jsp(288,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/purchase.jsp(288,2) '${clist}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${clist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/user/purchase.jsp(288,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("v");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<tr class=\"row\">\r\n");
          out.write("\t\t\t\t<td class=\"no\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${v.costume_cart_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${v.lend_costume_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${v.lend_costume_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t<td><img class=\"img\" src=\"../display?fileName=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${v.lend_costume_image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" width=110 onClick=\"location.href='/costume/costumeRead?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${v.lend_costume_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("'\"></td>\r\n");
          out.write("\t\t\t\t<td class=\"quantity\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${v.costume_cart_quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${v.costume_cart_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("원</td>\r\n");
          out.write("\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${v.costume_cart_price*v.costume_cart_quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("원</td>\r\n");
          out.write("\t\t\t</tr>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatNumber_005f0.setParent(null);
    // /WEB-INF/views/user/purchase.jsp(337,31) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(psum+csum)*0.01}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/views/user/purchase.jsp(337,31) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f0.setPattern("#,###");
    int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
    if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
    return false;
  }
}
