/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-08-27 00:35:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.read;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class couple_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>방울방울</title>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("\tfont-family: '@여기어때 잘난체';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#page {\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tmargin: 15px;\r\n");
      out.write("\tpadding-bottom: 30px;\r\n");
      out.write("\theight: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content {\r\n");
      out.write("\tmargin-top: none;\r\n");
      out.write("\tmargin-left: 70px;\r\n");
      out.write("\tmargin-right: 70px;\r\n");
      out.write("\tpadding: 30px margin-top: 10px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#couple1, #couple2, #couple3, #couple4, #couple5 {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tbl1 {\r\n");
      out.write("\twidth: 50%;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("\tmargin: 25px;\r\n");
      out.write("\tpadding: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title {\r\n");
      out.write("\tfont-size: 50px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#imgButton {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#menu {\r\n");
      out.write("\twidth: 760px;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#darken-background {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 0px;\r\n");
      out.write("\tleft: 0px;\r\n");
      out.write("\tright: 0px;\r\n");
      out.write("\theight: 0%;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tbackground: rgba(0, 0, 0, 0.5);\r\n");
      out.write("\tz-index: 10000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#lightbox {\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("\theight: 900px;\r\n");
      out.write("\tmargin: 20px auto;\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("\tborder: 1px solid #333333;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tbox-shadow: 0px 5px 5px rgba(34, 25, 25, 0.4);\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#perPage {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-top: 400px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tfont-size: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#nextPage {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tmargin-top: 400px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tfont-size: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btnClose {\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tfont-size: 50px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#lightbox img {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttop: 55px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"body\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/menu.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div id=\"page\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<div class=\"title\">⊙ COUPLE ⊙</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<table id=\"tbl1\">\r\n");
      out.write("\t\t\t\t<tr class=\"box\">\r\n");
      out.write("\t\t\t\t\t<td><img id=\"couple1\" page=\"1\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../display?fileName=couple-1.jpg\" width=500></td>\r\n");
      out.write("\t\t\t\t\t<td><img id=\"couple2\" page=\"2\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../display?fileName=couple-2.jpg\" width=500></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr class=\"box\">\r\n");
      out.write("\t\t\t\t\t<td colspan=2><img id=\"couple3\" page=\"3\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../display?fileName=couple-3.jpg\" width=1000></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr class=\"box\">\r\n");
      out.write("\t\t\t\t\t<td><img id=\"couple4\" page=\"4\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../display?fileName=couple-4.jpg\" width=500></td>\r\n");
      out.write("\t\t\t\t\t<td><img id=\"couple5\" page=\"5\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../display?fileName=couple-5.jpg\" width=500></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<img id=\"imgButton\" src=\"../display?fileName=예약하기.png\" width=300>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!--라이트 박스-->\r\n");
      out.write("\t<div id=\"darken-background\">\r\n");
      out.write("\t\t<div id=\"lightbox\">\r\n");
      out.write("\t\t\t<div style=\"text-align: right; margin-right: 10px;\">\r\n");
      out.write("\t\t\t\t<button id=\"btnClose\">X</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<button id=\"perPage\" disabled=\"false\">&lt</button>\r\n");
      out.write("\t\t\t<img id=\"lightImg\" />\r\n");
      out.write("\t\t\t<button id=\"nextPage\" disabled=\"false\">&gt</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../reservation/reservation.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/chat.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/top.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar src1 = \"../display?fileName=couple-\";\r\n");
      out.write("\tvar src2 = \".jpg\";\r\n");
      out.write("\tvar page;\r\n");
      out.write("\t$(\"#imgButton\").on(\"click\", function() {\r\n");
      out.write("\t\tlocation.href = \"/reservation/calendar\";\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\".box\").on(\"click\", \"img\", function() {\r\n");
      out.write("\t\tvar src = $(this).attr(\"src\");\r\n");
      out.write("\t\tpage = $(this).attr(\"page\");\r\n");
      out.write("\r\n");
      out.write("\t\tpageOnOff();\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#lightbox img\").attr(\"src\", src1 + page + src2);\r\n");
      out.write("\t\t$(\"#lightbox img\").attr(\"page\", page);\r\n");
      out.write("\t\t$(\"#darken-background\").show();\r\n");
      out.write("\t\tvar offset = $('.box').offset(); //선택한 태그의 위치를 반환\r\n");
      out.write("\t\t//animate()메서드를 이용해서 선택한 태그의 스크롤 위치를 지정해서 0.4초 동안 부드럽게 해당 위치로 이동함 \r\n");
      out.write("\t\t$('html').animate({\r\n");
      out.write("\t\t\tscrollTop : 0\r\n");
      out.write("\t\t}, 400);\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#btnClose\").on(\"click\", function() {\r\n");
      out.write("\t\t$(\"#darken-background\").hide();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#perPage\").on(\"click\", function() {\r\n");
      out.write("\t\tpage = $(\"#lightbox img\").attr(\"page\");\r\n");
      out.write("\t\tpage--;\r\n");
      out.write("\t\tvar src = src1 + page + src2;\r\n");
      out.write("\t\t$(\"#lightbox img\").attr(\"src\", src);\r\n");
      out.write("\t\t$(\"#lightbox img\").attr(\"page\", page);\r\n");
      out.write("\r\n");
      out.write("\t\tpageOnOff();\r\n");
      out.write("\t\tvar offset = $('.box').offset();\r\n");
      out.write("\t\t$('html').animate({\r\n");
      out.write("\t\t\tscrollTop : 0\r\n");
      out.write("\t\t}, 400);\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#nextPage\").on(\"click\", function() {\r\n");
      out.write("\t\tpage = $(\"#lightbox img\").attr(\"page\");\r\n");
      out.write("\t\tpage++;\r\n");
      out.write("\t\tvar src = src1 + page + src2;\r\n");
      out.write("\t\t$(\"#lightbox img\").attr(\"src\", src);\r\n");
      out.write("\t\t$(\"#lightbox img\").attr(\"page\", page);\r\n");
      out.write("\r\n");
      out.write("\t\tpageOnOff();\r\n");
      out.write("\t\tvar offset = $('.box').offset();\r\n");
      out.write("\t\t$('html').animate({\r\n");
      out.write("\t\t\tscrollTop : 0\r\n");
      out.write("\t\t}, 400);\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction pageOnOff() {\r\n");
      out.write("\t\tif (page == 1) {\r\n");
      out.write("\t\t\t$(\"#perPage\").attr(\"disabled\", true);\r\n");
      out.write("\t\t\t$(\"#nextPage\").attr(\"disabled\", false);\r\n");
      out.write("\t\t} else if (page == 5) {\r\n");
      out.write("\t\t\t$(\"#nextPage\").attr(\"disabled\", true);\r\n");
      out.write("\t\t\t$(\"#perPage\").attr(\"disabled\", false);\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$(\"#perPage\").attr(\"disabled\", false);\r\n");
      out.write("\t\t\t$(\"#nextPage\").attr(\"disabled\", false);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
