/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-07-30 07:28:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class packInsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>PHOTO_PACKAGE_INSERT</title>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("\tfont-family: '@여기어때 잘난체'\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#page {\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tmargin: 15px;\r\n");
      out.write("\tpadding-bottom: 30px;\r\n");
      out.write("\theight: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content {\r\n");
      out.write("\tmargin-top: none;\r\n");
      out.write("\tmargin-left: 70px;\r\n");
      out.write("\tmargin-right: 70px;\r\n");
      out.write("\tpadding: 30px;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tbl1 {\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".info {\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tpadding-left: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title {\r\n");
      out.write("\tfont-size: 50px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("select {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 25px;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\ttext-align-last: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("select option {\r\n");
      out.write("\theight: 25px;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\ttext-align-last: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart {\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\tfont-size: 35px;\r\n");
      out.write("\tmargin: 2px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tbackground: #e6bbea;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tborder-radius: 3px 3px 3px 3px;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart:active {\r\n");
      out.write("\tbackground: #cca6cf;\r\n");
      out.write("}\r\n");
      out.write("/*스타일 추가하기*/\r\n");
      out.write("input[type=file] {\r\n");
      out.write("\tvisibility: hidden;\r\n");
      out.write("\theight: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#listFile img {\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\tmargin-left: 15px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div id=\"page\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<div class=\"title\">⊙PHOTO_PACKAGE_INSERT⊙</div>\r\n");
      out.write("\t\t<br> <br>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<form name=\"frm\" action=\"packInsert\" method=\"post\"\r\n");
      out.write("\t\t\t\tenctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t<table id=\"tbl1\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>photo_package_code</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=400><input type=\"text\" name=\"photo_package_code\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"ex)Z001\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>photo_package_title</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=400><input type=\"text\" name=\"photo_package_title\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>photo_package_amount</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=400><input type=\"text\" name=\"photo_package_amount\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=1></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>photo_package_price</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=400><input type=\"text\" name=\"photo_package_price\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>photo_package_image</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=400><input type=\"file\" name=\"file\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tid=\"image\" src=\"http://placehold.it/150x120\" width=150 height=120>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=100><input type=\"button\" value=\"첨부이미지\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"btnImage\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td width=400 height=150><input type=\"file\" name=\"files\"\r\n");
      out.write("\t\t\t\t\t\t\taccept=\"image/*\" multiple>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"listFile\"></div></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"저장\"> <input type=\"reset\"\r\n");
      out.write("\t\t\t\t\tvalue=\"취소\"> <input type=\"button\" value=\"목록\" id=\"btnList\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "chat.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t//첨부이미지 버튼\r\n");
      out.write("\t$(\"#btnImage\").on(\"click\", function() {\r\n");
      out.write("\t\t$(frm.files).click();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t//목록버튼\r\n");
      out.write("\t$(\"#btnList\").on(\"click\", function() {\r\n");
      out.write("\t\tlocation.href = \"costumeList\";\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t//이미지 클릭했을떄\r\n");
      out.write("\t$(\"#image\").on(\"click\", function() { //이미지클릭할때 file클릭한거처럼 됨\r\n");
      out.write("\t\t$(frm.file).click();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t//파일업로드\r\n");
      out.write("\t$(frm.file).on(\"change\", function() {\r\n");
      out.write("\t\tvar file = $(frm.file)[0].files[0]; //1번째 input type=\"file\"에서 이미지 1개만\r\n");
      out.write("\t\t$(\"#image\").attr(\"src\", URL.createObjectURL(file));\r\n");
      out.write("\t\tvar src = $(\"#image\").attr(\"src\");\r\n");
      out.write("\t\talert(src);\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t//파일업로드(여러개)\r\n");
      out.write("\t$(frm.files).on(\"change\", function() {\r\n");
      out.write("\t\tvar files = $(frm.files)[0].files;\r\n");
      out.write("\t\tvar html = \"\";\r\n");
      out.write("\t\t$.each(files, function(index, file) {\r\n");
      out.write("\t\t\thtml += \"<img src='\" + URL.createObjectURL(file) + \"'>\";\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#listFile\").html(html);\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
